name: OWHOfflineTeleport
main: me.insom.optp.core.OWHOfflinePlayerTeleport
version: 1.0

commands:
  offlinetp:
    description: "Teleport to offline players!"
    usage: "/offlinetp <player>"
    aliases: [otp]
  offlinetphere:
    description: "Teleport offline players to you!"
    usage: "/offlinetphere <player>"
    aliases: [otphere]
  toggleofflinetp:
    description: "Disable/enable the ability for others to tp to you"
    usage: "/totp"
    aliases: [totp]